const styles = {
  app: {
    minHeight: "100vh",
    background: "#f0faf4",
    fontFamily: "'Segoe UI', sans-serif",
    padding: "2rem",
    maxWidth: "680px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    marginBottom: "2rem",
  },
  logo: {
    fontSize: "2rem",
    fontWeight: "700",
    color: "#1a6b3c",
    margin: 0,
  },
  leaf: { fontSize: "1.8rem" },
  card: {
    background: "#ffffff",
    borderRadius: "16px",
    padding: "1.5rem",
    marginBottom: "1.5rem",
    boxShadow: "0 2px 12px rgba(26,107,60,0.08)",
    border: "1px solid #d4edda",
  },
  cardTitle: {
    fontSize: "1.1rem",
    fontWeight: "600",
    color: "#1a6b3c",
    marginBottom: "1.25rem",
    marginTop: 0,
  },
  field: { marginBottom: "1rem" },
  label: {
    display: "block",
    fontSize: "0.85rem",
    fontWeight: "500",
    color: "#4a7c59",
    marginBottom: "0.4rem",
  },
  input: {
    width: "100%",
    padding: "0.6rem 0.9rem",
    borderRadius: "10px",
    border: "1.5px solid #b7ddc4",
    fontSize: "1rem",
    color: "#1a3a26",
    background: "#f7fdf9",
    boxSizing: "border-box",
    outline: "none",
  },
  select: {
    width: "100%",
    padding: "0.6rem 0.9rem",
    borderRadius: "10px",
    border: "1.5px solid #b7ddc4",
    fontSize: "1rem",
    color: "#1a3a26",
    background: "#f7fdf9",
    boxSizing: "border-box",
    outline: "none",
  },
  button: {
    width: "100%",
    padding: "0.85rem",
    borderRadius: "12px",
    border: "none",
    background: "#1a6b3c",
    color: "#ffffff",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    marginTop: "0.5rem",
  },
  userRow: {
    display: "flex",
    gap: "0.75rem",
    alignItems: "flex-end",
  },
  userInput: { flex: 1 },
  loadBtn: {
    padding: "0.6rem 1.2rem",
    borderRadius: "10px",
    border: "1.5px solid #1a6b3c",
    background: "transparent",
    color: "#1a6b3c",
    fontSize: "0.95rem",
    fontWeight: "600",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  habitItem: {
    background: "#f7fdf9",
    borderRadius: "12px",
    padding: "1rem 1.25rem",
    marginBottom: "0.75rem",
    border: "1px solid #d4edda",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "0.4rem 1.5rem",
  },
  habitStat: { fontSize: "0.9rem", color: "#2d5a3e" },
  statLabel: { fontWeight: "600", color: "#1a6b3c" },
  empty: { color: "#7aab8a", fontSize: "0.95rem", textAlign: "center", padding: "1rem 0" },
  successMsg: {
    background: "#d4edda",
    color: "#1a6b3c",
    borderRadius: "10px",
    padding: "0.6rem 1rem",
    fontSize: "0.9rem",
    marginTop: "0.75rem",
    textAlign: "center",
  }
}

export default styles;